version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: court_portal
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: court-portal-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:123456@db:5432/court_portal?sslmode=disable
      - PORT=3000
      - NODE_ENV=production
      - JWT_SECRET=super-secret-key-12345
      - JWT_REFRESH_SECRET=another-super-secret-key-12345
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - db
    command: sh -c "npx prisma db push --accept-data-loss && node server/index.js"

volumes:
  postgres_data:
